require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/hashtags", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Hashtag. As you add validations to Hashtag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Hashtag.create! valid_attributes
      get hashtags_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hashtag = Hashtag.create! valid_attributes
      get hashtag_url(hashtag)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hashtag_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      hashtag = Hashtag.create! valid_attributes
      get edit_hashtag_url(hashtag)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Hashtag" do
        expect {
          post hashtags_url, params: { hashtag: valid_attributes }
        }.to change(Hashtag, :count).by(1)
      end

      it "redirects to the created hashtag" do
        post hashtags_url, params: { hashtag: valid_attributes }
        expect(response).to redirect_to(hashtag_url(Hashtag.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Hashtag" do
        expect {
          post hashtags_url, params: { hashtag: invalid_attributes }
        }.to change(Hashtag, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post hashtags_url, params: { hashtag: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hashtag" do
        hashtag = Hashtag.create! valid_attributes
        patch hashtag_url(hashtag), params: { hashtag: new_attributes }
        hashtag.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hashtag" do
        hashtag = Hashtag.create! valid_attributes
        patch hashtag_url(hashtag), params: { hashtag: new_attributes }
        hashtag.reload
        expect(response).to redirect_to(hashtag_url(hashtag))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        hashtag = Hashtag.create! valid_attributes
        patch hashtag_url(hashtag), params: { hashtag: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hashtag" do
      hashtag = Hashtag.create! valid_attributes
      expect {
        delete hashtag_url(hashtag)
      }.to change(Hashtag, :count).by(-1)
    end

    it "redirects to the hashtags list" do
      hashtag = Hashtag.create! valid_attributes
      delete hashtag_url(hashtag)
      expect(response).to redirect_to(hashtags_url)
    end
  end
end
