require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/nations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Nation. As you add validations to Nation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Nation.create! valid_attributes
      get nations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      nation = Nation.create! valid_attributes
      get nation_url(nation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_nation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      nation = Nation.create! valid_attributes
      get edit_nation_url(nation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Nation" do
        expect {
          post nations_url, params: { nation: valid_attributes }
        }.to change(Nation, :count).by(1)
      end

      it "redirects to the created nation" do
        post nations_url, params: { nation: valid_attributes }
        expect(response).to redirect_to(nation_url(Nation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Nation" do
        expect {
          post nations_url, params: { nation: invalid_attributes }
        }.to change(Nation, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post nations_url, params: { nation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested nation" do
        nation = Nation.create! valid_attributes
        patch nation_url(nation), params: { nation: new_attributes }
        nation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the nation" do
        nation = Nation.create! valid_attributes
        patch nation_url(nation), params: { nation: new_attributes }
        nation.reload
        expect(response).to redirect_to(nation_url(nation))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        nation = Nation.create! valid_attributes
        patch nation_url(nation), params: { nation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested nation" do
      nation = Nation.create! valid_attributes
      expect {
        delete nation_url(nation)
      }.to change(Nation, :count).by(-1)
    end

    it "redirects to the nations list" do
      nation = Nation.create! valid_attributes
      delete nation_url(nation)
      expect(response).to redirect_to(nations_url)
    end
  end
end
