require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/violations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Violation. As you add validations to Violation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Violation.create! valid_attributes
      get violations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      violation = Violation.create! valid_attributes
      get violation_url(violation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_violation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      violation = Violation.create! valid_attributes
      get edit_violation_url(violation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Violation" do
        expect {
          post violations_url, params: { violation: valid_attributes }
        }.to change(Violation, :count).by(1)
      end

      it "redirects to the created violation" do
        post violations_url, params: { violation: valid_attributes }
        expect(response).to redirect_to(violation_url(Violation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Violation" do
        expect {
          post violations_url, params: { violation: invalid_attributes }
        }.to change(Violation, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post violations_url, params: { violation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested violation" do
        violation = Violation.create! valid_attributes
        patch violation_url(violation), params: { violation: new_attributes }
        violation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the violation" do
        violation = Violation.create! valid_attributes
        patch violation_url(violation), params: { violation: new_attributes }
        violation.reload
        expect(response).to redirect_to(violation_url(violation))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        violation = Violation.create! valid_attributes
        patch violation_url(violation), params: { violation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested violation" do
      violation = Violation.create! valid_attributes
      expect {
        delete violation_url(violation)
      }.to change(Violation, :count).by(-1)
    end

    it "redirects to the violations list" do
      violation = Violation.create! valid_attributes
      delete violation_url(violation)
      expect(response).to redirect_to(violations_url)
    end
  end
end
