# :verbose: false
# :dynamic: true

running_auto_generator:
  cron: "* * * * *"
  class: "AutoGeneratorJob"
  queue: default

scan_violation:
  cron: "*/5 * * * *"
  class: "ViolationJob"
  queue: default

update_hash_tag:
  cron: "*/5 * * * *"
  class: "HashtagJob"
  queue: high_priority

# development:
#   :concurrency: 25
# staging:
#   :concurrency: 12
# production:
#   :concurrency: 25
# :queues:
# - [default, 1]
# - [high_priority, 10]